channel_list = [
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png", "tvg-name": "CCTV1", "name": "CCTV-1综合"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV2.png", "tvg-name": "CCTV2", "name": "CCTV-2财经"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV3.png", "tvg-name": "CCTV3", "name": "CCTV-3综艺"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV4.png", "tvg-name": "CCTV4", "name": "CCTV-4中文国际"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV5.png", "tvg-name": "CCTV5", "name": "CCTV-5体育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV5+.png", "tvg-name": "CCTV5+", "name": "CCTV-5+体育赛事"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV6.png", "tvg-name": "CCTV6", "name": "CCTV-6电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV7.png", "tvg-name": "CCTV7", "name": "CCTV-7国防军事"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV8.png", "tvg-name": "CCTV8", "name": "CCTV-8电视剧"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV9.png", "tvg-name": "CCTV9", "name": "CCTV-9纪录"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV10.png", "tvg-name": "CCTV10", "name": "CCTV-10科教"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV11.png", "tvg-name": "CCTV11", "name": "CCTV-11戏曲"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV12.png", "tvg-name": "CCTV12", "name": "CCTV-12社会与法"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV13.png", "tvg-name": "CCTV13", "name": "CCTV-13新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV14.png", "tvg-name": "CCTV14", "name": "CCTV-14少儿"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV15.png", "tvg-name": "CCTV15", "name": "CCTV-15音乐"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV17.png", "tvg-name": "CCTV17", "name": "CCTV-17农村农业"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/cgtn.png", "tvg-name": "CGTN", "name": "CGTN"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV4EUO.png", "tvg-name": "CCTV4EUO", "name": "CCTV-4欧洲"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV4AME.png", "tvg-name": "CCTV4AME", "name": "CCTV-4美洲"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/hunan.png", "tvg-name": "湖南卫视", "name": "湖南卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/zhejiang.png", "tvg-name": "浙江卫视", "name": "浙江卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/jiangsu.png", "tvg-name": "江苏卫视", "name": "江苏卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/beijing.png", "tvg-name": "北京卫视", "name": "北京卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/dongfang.png", "tvg-name": "东方卫视", "name": "东方卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/anhui.png", "tvg-name": "安徽卫视", "name": "安徽卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/guangdong.png", "tvg-name": "广东卫视", "name": "广东卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/shenzhen.png", "tvg-name": "深圳卫视", "name": "深圳卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/liaoning.png", "tvg-name": "辽宁卫视", "name": "辽宁卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/lvyou.png", "tvg-name": "旅游卫视", "name": "海南卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/shandong.png", "tvg-name": "山东卫视", "name": "山东卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/tianjin.png", "tvg-name": "天津卫视", "name": "天津卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/chongqing.png", "tvg-name": "重庆卫视", "name": "重庆卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/dongnan.png", "tvg-name": "东南卫视", "name": "东南卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/gansu.png", "tvg-name": "甘肃卫视", "name": "甘肃卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/guangxi.png", "tvg-name": "广西卫视", "name": "广西卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/guizhou.png", "tvg-name": "贵州卫视", "name": "贵州卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/hebei.png", "tvg-name": "河北卫视", "name": "河北卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/heilongjiang.png", "tvg-name": "黑龙江卫视", "name": "黑龙江卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/henan.png", "tvg-name": "河南卫视", "name": "河南卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/hubei.png", "tvg-name": "湖北卫视", "name": "湖北卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/jiangxi.png", "tvg-name": "江西卫视", "name": "江西卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/jilin.png", "tvg-name": "吉林卫视", "name": "吉林卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/neimeng.png", "tvg-name": "内蒙古卫视", "name": "内蒙古卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/ningxia.png", "tvg-name": "宁夏卫视", "name": "宁夏卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/shanxi_.png", "tvg-name": "山西卫视", "name": "山西卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/shanxi.png", "tvg-name": "陕西卫视", "name": "陕西卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/sichuan.png", "tvg-name": "四川卫视", "name": "四川卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/xinjiang.png", "tvg-name": "新疆卫视", "name": "新疆卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/yunnan.png", "tvg-name": "云南卫视", "name": "云南卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/qinghai.png", "tvg-name": "青海卫视", "name": "青海卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/bingtuan.png", "tvg-name": "兵团卫视", "name": "兵团卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/xuandong.png", "tvg-name": "哈哈炫动", "name": "哈哈炫动"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/YANBIAN1.png", "tvg-name": "延边卫视", "name": "延边卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/huanghe.png", "tvg-name": "黄河卫视", "name": "黄河卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/kaku.png", "tvg-name": "卡酷动画", "name": "卡酷动画"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/xiamen.png", "tvg-name": "厦门卫视", "name": "厦门卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/jinyingkatong.png", "tvg-name": "金鹰卡通", "name": "金鹰卡通"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/kangba.png", "tvg-name": "康巴卫视", "name": "康巴卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/xizang.png", "tvg-name": "西藏卫视", "name": "西藏卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/sansha.png", "tvg-name": "三沙卫视", "name": "三沙卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/中国教育1台.png", "tvg-name": "中国教育1台", "name": "中国教育1台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/中国教育2台.png", "tvg-name": "中国教育2台", "name": "中国教育2台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/中国教育3台.png", "tvg-name": "中国教育3台", "name": "中国教育3台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV3D.png", "tvg-name": "3D电视试验频道",
     "name": "中国3D电视试验频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTVEFEL.png", "tvg-name": "外汇理财", "name": "外汇理财"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/dianjingtiantang.png", "tvg-name": "电竞天堂", "name": "电竞天堂"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV5+.png", "tvg-name": "IPTV5+", "name": "IPTV5+"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV6+.png", "tvg-name": "IPTV6+", "name": "IPTV6+"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV经典电影.png", "tvg-name": "IPTV经典电影",
     "name": "IPTV经典电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV热播剧场.png", "tvg-name": "IPTV热播剧场",
     "name": "IPTV热播剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV少儿动画.png", "tvg-name": "IPTV少儿动画",
     "name": "IPTV少儿动画"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/IPTV魅力时尚.png", "tvg-name": "IPTV魅力时尚",
     "name": "IPTV魅力时尚"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV4k.png", "tvg-name": "CCTV4K", "name": "CCTV4K"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVB翡翠台.png", "tvg-name": "翡翠台", "name": "翡翠台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVB明珠台.png", "tvg-name": "明珠台", "name": "明珠台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBclassic.png", "tvg-name": "TVB经典台", "name": "千禧經典台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/wxxw.png", "tvg-name": "无线新闻", "name": "无线新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tvbfinanceinformationchannel.png", "tvg-name": "无线财经",
     "name": "无线财经体育资讯台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/fenghuangzhongwen.png", "tvg-name": "凤凰中文",
     "name": "凤凰卫视中文台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/fenghuangzixun.png", "tvg-name": "凤凰资讯",
     "name": "凤凰卫视资讯台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/fenghuangxianggang.png", "tvg-name": "凤凰香港",
     "name": "凤凰卫视香港台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/yangguangweishi.png", "tvg-name": "阳光卫视", "name": "阳光卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/meiyamovie.png", "tvg-name": "美亚高清电影台",
     "name": "美亚高清电影台(香港)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NHKWorld.png", "tvg-name": "NHKWorld", "name": "NHK,World,TV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/viutv.png", "tvg-name": "ViuTV", "name": "Viu,TV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/hks.png", "tvg-name": "HKS", "name": "香港卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBJ2.png", "tvg-name": "J2", "name": "J2"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/natgeowild.png", "tvg-name": "国家地理野生频道",
     "name": "国家地理野生频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/mezzo.png", "tvg-name": "MEZZOLIVEHD", "name": "MEZZO,LIVE,HD"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Lifetime.png", "tvg-name": "Lifetime", "name": "Lifetime,娱乐频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/starmov.png", "tvg-name": "星卫HD电影", "name": "星卫HD电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EbcAsiaNews.png", "tvg-name": "东森亚洲新闻台",
     "name": "东森亚洲新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EbcAsiaWeishi.png", "tvg-name": "东森亚洲卫视",
     "name": "东森亚洲卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/PublicTV2.png", "tvg-name": "公视2", "name": "公视台语台(公视2)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GoodTV2.png", "tvg-name": "GoodTV2", "name": "好消息二台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/chuangshi.png", "tvg-name": "创世电视", "name": "创世电视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NEXTTVZonghe.png", "tvg-name": "壹电视综合台",
     "name": "壹电视综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NEXTTVMovie.png", "tvg-name": "壹电视电影台",
     "name": "壹电视电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BBCWORLDNEWSASIA.png", "tvg-name": "BBCWorldNews",
     "name": "BBC,World,News"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CNCartoon.png", "tvg-name": "CN卡通频道", "name": "CN卡通频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CNBC.png", "tvg-name": "CNBCHongKong", "name": "CNBC亚太财经"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/natgeo.png", "tvg-name": "国家地理频道", "name": "国家地理频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/faguoshishang.png", "tvg-name": "FashionTV", "name": "法国时尚台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BabyTV.png", "tvg-name": "BabyTV", "name": "Baby,TV(台湾)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FXHD.png", "tvg-name": "FXHD", "name": "FX,HD"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/DW.png", "tvg-name": "DW", "name": "DW德国之声(ENGLISH)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tv5monde.png", "tvg-name": "TV5Monde", "name": "法国TV5Monde"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/france24.png", "tvg-name": "france24", "name": "法国24台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SkyNews.png", "tvg-name": "SkyNews", "name": "Sky,News"},
    {"tvg-logo": "https://pic.4gtv.tv/ChannelLogo/mobile/logo_4gtv_4gtv-4gtv112_mobile.png", "tvg-name": "天映经典",
     "name": "天映经典频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/cinemaworld.png", "tvg-name": "cinemaworld", "name": "cinemaworld"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CGTNDoc.png", "tvg-name": "CGTNDocumentary",
     "name": "CGTN,纪录(英)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TRACESportStars.png", "tvg-name": "TraceSports",
     "name": "Trace,Sports"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/outdoor.png", "tvg-name": "Outdoor", "name": "Outdoor,Channel"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HITS.png", "tvg-name": "HITS", "name": "HITS"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/youman.png", "tvg-name": "优漫卡通", "name": "优漫卡通"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/gtv_youxi.png", "tvg-name": "GTV游戏竞技", "name": "GTV游戏竞技"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/xindongman.png", "tvg-name": "新动漫", "name": "新动漫"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_qilu.png", "tvg-name": "山东齐鲁", "name": "山东齐鲁"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_tiyu.png", "tvg-name": "山东体育", "name": "山东体育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_nongke.png", "tvg-name": "山东农科", "name": "山东农科"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_gonggong.png", "tvg-name": "山东公共", "name": "山东公共"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_shaoer.png", "tvg-name": "山东少儿", "name": "山东少儿"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_yingshi.png", "tvg-name": "山东影视", "name": "山东影视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_zongyi.png", "tvg-name": "山东综艺", "name": "山东综艺"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_shenghuo.png", "tvg-name": "山东生活", "name": "山东生活"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/sd_huanyudianying.jpg", "tvg-name": "环宇电影", "name": "环宇电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI2.png", "tvg-name": "湖北综合频道", "name": "湖北综合频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI3.png", "tvg-name": "湖北影视频道", "name": "湖北影视频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI4.png", "tvg-name": "湖北教育频道", "name": "湖北教育频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI5.png", "tvg-name": "湖北生活频道", "name": "湖北生活频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI7.png", "tvg-name": "湖北公共·新闻", "name": "湖北公共·新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUBEI8.png", "tvg-name": "湖北经济频道", "name": "湖北经济频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HBLS.png", "tvg-name": "湖北垄上频道", "name": "湖北垄上频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV1.png", "tvg-name": "武汉新闻综合频道",
     "name": "武汉新闻综合频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV2.png", "tvg-name": "武汉电视剧频道", "name": "武汉电视剧频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV3.png", "tvg-name": "武汉科技生活频道",
     "name": "武汉科技生活频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV4.png", "tvg-name": "武汉经济频道", "name": "武汉经济频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV5.png", "tvg-name": "武汉文体频道", "name": "武汉文体频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV6.png", "tvg-name": "武汉外语频道", "name": "武汉外语频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WHTV7.png", "tvg-name": "武汉少儿频道", "name": "武汉少儿频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WETV.png", "tvg-name": "武汉教育电视台", "name": "武汉教育电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/beijingjishi.png", "tvg-name": "北京纪实", "name": "北京冬奥纪实"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV文艺.png", "tvg-name": "BTV文艺", "name": "BTV文艺"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV科教.png", "tvg-name": "BTV科教", "name": "BTV科教"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV影视.png", "tvg-name": "BTV影视", "name": "BTV影视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV财经.png", "tvg-name": "BTV财经", "name": "BTV财经"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV体育.png", "tvg-name": "BTV体育", "name": "BTV体育休闲"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV生活.png", "tvg-name": "BTV生活", "name": "BTV生活"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/BTV新闻.png", "tvg-name": "BTV新闻", "name": "BTV新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/DOX_YAQU.png", "tvg-name": "DOX雅趣", "name": "DOX雅趣"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/qicaixiju.png", "tvg-name": "七彩戏剧", "name": "七彩戏剧"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/xinshijue.png", "tvg-name": "新视觉", "name": "新视觉"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/jinbaotiyu.jpg", "tvg-name": "劲爆体育", "name": "劲爆体育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/dox_yinglun.png", "tvg-name": "DOX英伦", "name": "DOX英伦"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/dox_juchang.png", "tvg-name": "DOX剧场", "name": "DOX剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/quanjishi.png", "tvg-name": "全纪实", "name": "乐游"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/huanxiao.png", "tvg-name": "欢笑剧场", "name": "欢笑剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/xingfucai.png", "tvg-name": "幸福彩", "name": "幸福彩"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/shenghuoshishang.png", "tvg-name": "生活时尚", "name": "生活时尚"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/youxifengyun.png", "tvg-name": "游戏风云", "name": "游戏风云"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/shangshixinwen.png", "tvg-name": "上视新闻频道",
     "name": "上视新闻频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/diyicaijing.png", "tvg-name": "第一财经", "name": "第一财经"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/shanghaidongfangyingshi.png", "tvg-name": "东方影视",
     "name": "东方影视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/wuxingtiyu.png", "tvg-name": "五星体育频道",
     "name": "五星体育频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/shanghaijishi.png", "tvg-name": "上海纪实", "name": "上海纪实人文"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/shanghaidushi.jpg", "tvg-name": "上海都市频道",
     "name": "上海都市频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/zgjt.png", "tvg-name": "中国交通频道", "name": "中国交通频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/ws/jinyingjishi.png", "tvg-name": "金鹰纪实", "name": "金鹰纪实"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv2.png", "tvg-name": "SCTV2", "name": "四川文化旅游"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv3.png", "tvg-name": "SCTV3", "name": "四川经济"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv4.png", "tvg-name": "SCTV4", "name": "四川新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv5.png", "tvg-name": "SCTV5", "name": "四川影视文艺频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv7.png", "tvg-name": "SCTV7", "name": "四川妇女儿童频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/emeidianying.png", "tvg-name": "峨嵋电影", "name": "峨嵋电影频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv9.png", "tvg-name": "SCTV9", "name": "四川公共频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/sctv8.png", "tvg-name": "SCTV8", "name": "四川科教频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv1.png", "tvg-name": "CDTV1", "name": "成都新闻综合频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv2.png", "tvg-name": "CDTV2", "name": "成都经济资讯频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv3.png", "tvg-name": "CDTV3", "name": "成都都市生活频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv4.png", "tvg-name": "CDTV4", "name": "成都影视文艺频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv5.png", "tvg-name": "CDTV5", "name": "成都公共频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/cdtv6.png", "tvg-name": "CDTV6", "name": "成都少儿频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVfengyunzuqiu.png", "tvg-name": "风云足球",
     "name": "中数风云足球"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV2.png", "tvg-name": "辽宁都市", "name": "辽宁都市"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV3.png", "tvg-name": "辽宁影视剧", "name": "辽宁影视剧"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV5.png", "tvg-name": "辽宁青少", "name": "辽宁青少"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV6.png", "tvg-name": "辽宁生活", "name": "辽宁生活"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV7.png", "tvg-name": "辽宁公共", "name": "辽宁公共"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV8.png", "tvg-name": "辽宁北方", "name": "辽宁北方"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV-SPORT.png", "tvg-name": "辽宁体育", "name": "辽宁体育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNTV-FINANCE.png", "tvg-name": "辽宁经济", "name": "辽宁经济"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/LNSY1.png", "tvg-name": "沈阳新闻", "name": "沈阳新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/jiajiakt.png", "tvg-name": "嘉佳卡通", "name": "嘉佳卡通"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTV3.png", "tvg-name": "广东体育", "name": "广东体育频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTV4.png", "tvg-name": "广东公共", "name": "广东公共频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/zhujiang.png", "tvg-name": "珠江海外", "name": "珠江频道海外版"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTV6.png", "tvg-name": "广东新闻", "name": "广东新闻频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTV8.png", "tvg-name": "广东国际", "name": "广东国际频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/PublicTV3HD.png", "tvg-name": "公视三台", "name": "公视三台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CNNNews.png", "tvg-name": "CNN", "name": "CNN国际新闻频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FTV.png", "tvg-name": "民视无线台", "name": "民视无线台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/台视.png", "tvg-name": "台视", "name": "台视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/daai.png", "tvg-name": "大爱一台", "name": "大爱电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/中视.png", "tvg-name": "中视", "name": "中视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png", "tvg-name": "人间卫视", "name": "人间卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CTS.png", "tvg-name": "华视", "name": "华视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/PublicTV.png", "tvg-name": "公视", "name": "公视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GoodTV.png", "tvg-name": "GoodTV", "name": "好消息频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/yuanzhumin.png", "tvg-name": "原住民频道", "name": "原住民频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HakkaTV.png", "tvg-name": "客家电视台", "name": "客家电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NationalGeographic_taiwan.png", "tvg-name": "国家地理频道(台湾)",
     "name": "国家地理频道(台湾)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/DiscoveryHD.png", "tvg-name": "Discovery", "name": "探索发现频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tlc.png", "tvg-name": "TLC旅游生活频道", "name": "TLC旅游生活频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/AnimalPlanet.png", "tvg-name": "动物星球", "name": "动物星球"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Disney.png", "tvg-name": "Disney", "name": "迪士尼频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/MOMOkids.png", "tvg-name": "MOMO亲子台", "name": "MOMO亲子台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCYoYoTV.png", "tvg-name": "东森幼幼台", "name": "东森幼幼台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandOnTV.png", "tvg-name": "纬来综合台", "name": "纬来综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GTVOneHD.png", "tvg-name": "八大第一台", "name": "八大第一台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GTVVarietyHD.png", "tvg-name": "八大综合台", "name": "八大综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SETTaiwan.png", "tvg-name": "三立台湾台", "name": "三立台湾台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SETCity.png", "tvg-name": "三立都会台", "name": "三立都会台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/卫视中文.png", "tvg-name": "卫视中文台", "name": "卫视中文台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCVariety.png", "tvg-name": "东森综合台", "name": "东森综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCSuper.png", "tvg-name": "东森超视", "name": "东森超视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CtiVariety.png", "tvg-name": "中天综合台", "name": "中天综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/东风卫视.png", "tvg-name": "东风卫视", "name": "东风卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/年代MUCH.png", "tvg-name": "年代MUCH", "name": "年代MUCH,TV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CtiEntertainment.png", "tvg-name": "中天娱乐台",
     "name": "中天娱乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCDrama.png", "tvg-name": "东森戏剧台", "name": "东森戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GTVDramaHD.png", "tvg-name": "八大戏剧台", "name": "八大戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBS欢乐.png", "tvg-name": "TVBS欢乐台", "name": "TVBS欢乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandDrama.png", "tvg-name": "纬来戏剧台",
     "name": "纬来戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TOPTVHD.png", "tvg-name": "高点综合台", "name": "高点电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/JETVariety.png", "tvg-name": "JET综合台", "name": "JET综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NextTVNews.png", "tvg-name": "壹电视新闻台",
     "name": "壹电视新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/年代ERANewsHD.png", "tvg-name": "年代新闻台", "name": "年代新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCNews.png", "tvg-name": "东森新闻台", "name": "东森新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FTVNews.png", "tvg-name": "民视新闻台", "name": "民视新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SETNews.png", "tvg-name": "三立新闻台", "name": "三立新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBS新闻.png", "tvg-name": "TVBS新闻台", "name": "TVBS,新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBS.png", "tvg-name": "TVBS", "name": "TVBS"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCFinancialNews.png", "tvg-name": "东森财经新闻台",
     "name": "东森财经新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/UniqueNews.png", "tvg-name": "非凡新闻台", "name": "非凡新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/StarChineseMovies.png", "tvg-name": "卫视电影台",
     "name": "卫视电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCMovies.png", "tvg-name": "东森电影台", "name": "东森电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandMovies.png", "tvg-name": "纬来电影台",
     "name": "纬来电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/LSTIME.png", "tvg-name": "LSTime电影台",
     "name": "LS,Time龙祥時代电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HBO.png", "tvg-name": "HBO", "name": "HBO"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EBCWesternMovies.png", "tvg-name": "东森洋片台",
     "name": "东森洋片台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/AXN.png", "tvg-name": "AXN", "name": "AXN"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HMC.png", "tvg-name": "好莱坞电影台", "name": "好莱坞电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FOXMOVIES.png", "tvg-name": "FOXMOVIES", "name": "FOX,MOVIES"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandMaxTV.png", "tvg-name": "纬来育乐台",
     "name": "纬来育乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CinemaxHD.png", "tvg-name": "CINEMAX", "name": "CINEMAX"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandSportsHD.png", "tvg-name": "纬来体育台",
     "name": "纬来体育台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FOXSports.png", "tvg-name": "FOXSports", "name": "FOX,Sports"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ELEVENsports1.png", "tvg-name": "ELEVEN体育一台",
     "name": "ELEVEN体育一台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/VideolandJapanese.png", "tvg-name": "纬来日本台",
     "name": "纬来日本台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GoldSunTV.png", "tvg-name": "国兴卫视", "name": "国兴卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FOXHD.png", "tvg-name": "FOX", "name": "FOX"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天综合.png", "tvg-name": "靖天综合台", "name": "靖天综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天资讯.png", "tvg-name": "靖天资讯台", "name": "靖天资讯台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SinJiTVHD.png", "tvg-name": "信吉电视台", "name": "信吉电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖洋戏剧.png", "tvg-name": "靖洋戏剧台", "name": "靖洋戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TACT.png", "tvg-name": "台湾艺术台", "name": "台湾艺术台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CostarTV.png", "tvg-name": "全大电视台", "name": "全大电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/UniqueUSTVHDUSTVHD.png", "tvg-name": "非凡商业台",
     "name": "非凡商业台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SETInews.png", "tvg-name": "三立财经新闻台",
     "name": "三立财经新闻台inews"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EFTV.png", "tvg-name": "运通财经", "name": "运通财经"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SBN.png", "tvg-name": "SBN全球财经台", "name": "SBN全球财经台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ChengSinTV.png", "tvg-name": "诚心电视台", "name": "诚心电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NHK.png", "tvg-name": "NHK", "name": "NHK"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/mtvlivehd.png", "tvg-name": "MTV", "name": "MTV,Live,HD,音乐频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天映画.png", "tvg-name": "靖天映画", "name": "靖天映画"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/海豚综合.png", "tvg-name": "海豚综合台", "name": "海豚综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/PiliPuppet.png", "tvg-name": "霹雳台湾台", "name": "霹雳台湾台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CosmosBuddhistMissionaryTV.png", "tvg-name": "十方法界",
     "name": "十方法界"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SinDaTV.png", "tvg-name": "信大频道", "name": "信大频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HwaZanTV.png", "tvg-name": "华藏卫视", "name": "华藏卫视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ZChannel.png", "tvg-name": "Z频道", "name": "Z频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BudddhaCompassionTV.png", "tvg-name": "佛卫慈悲台",
     "name": "佛卫慈悲台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/shengming.png", "tvg-name": "生命频道", "name": "生命频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TienLiangTVHD.png", "tvg-name": "天良综合台", "name": "天良综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ChengTeTV.png", "tvg-name": "正德电视台", "name": "正德电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TOPTV2.png", "tvg-name": "高点育乐台", "name": "高点育乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ChampionTV2.png", "tvg-name": "冠军梦想台", "name": "冠军梦想台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GTVEntertainment.png", "tvg-name": "八大娱乐台",
     "name": "八大娱乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/DaliTV.png", "tvg-name": "大立电视台", "name": "大立电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/gstv.png", "tvg-name": "幸福空间居家台", "name": "幸福空间居家台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/channelnewsasia.png", "tvg-name": "ChannelNewsAsia",
     "name": "亚洲新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BloombergTV.png", "tvg-name": "BloombergTV", "name": "彭博财经台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ArirangTV.png", "tvg-name": "ArirangTV", "name": "韩国阿里郎"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/daai2.png", "tvg-name": "大爱二台", "name": "大爱二台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/台视新闻.png", "tvg-name": "台视新闻台", "name": "台视新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/台视财经.png", "tvg-name": "台视财经台", "name": "台视财经台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/台视综合.png", "tvg-name": "台视综合台", "name": "台视综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BBCLifestyle.png", "tvg-name": "BBCLifestyle",
     "name": "BBC,Lifestyle(高清)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/dreamworks.png", "tvg-name": "DREAMWORKS", "name": "梦工厂"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/WarnerTV.png", "tvg-name": "WarnerTV", "name": "Warner,TV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天欢乐.png", "tvg-name": "靖天欢乐台", "name": "靖天欢乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天育乐.png", "tvg-name": "靖天育乐台", "name": "靖天育乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HBOHD.png", "tvg-name": "HBOHD", "name": "HBO,HD"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HBOHits.png", "tvg-name": "HBOHits", "name": "HBO,强档钜献"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HBOSignature.png", "tvg-name": "HBOSignature",
     "name": "HBO,原创钜献"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HBOFamily.png", "tvg-name": "HBOFamily", "name": "HBO,温馨家庭"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BlueAntEntertainment.png", "tvg-name": "BlueAntEntertainment",
     "name": "BlueAnt综艺娱乐"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天日本.png", "tvg-name": "靖天日本台", "name": "靖天日本台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/FoodNetwork.png", "tvg-name": "FoodNetwork美食台",
     "name": "Food,Network美食台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tvN.png", "tvg-name": "tvN", "name": "tvN"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/KMTV.png", "tvg-name": "韩国娱乐台KMTV", "name": "韩国娱乐台KMTV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/EVE.png", "tvg-name": "EVE", "name": "EVE"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Discovery科学.png", "tvg-name": "Discovery科学",
     "name": "Discovery,科学频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Discovery-Asia.png", "tvg-name": "DiscoveryAsia",
     "name": "Discovery,Asia"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HGTV.png", "tvg-name": "HGTV居家乐活", "name": "HGTV居家乐活"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/travelchannel.png", "tvg-name": "TravelChannel",
     "name": "Travel,Channel"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/afc.png", "tvg-name": "亚洲美食频道", "name": "亚洲美食频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/DMAX.png", "tvg-name": "DMAX", "name": "DMAX(高清)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/GlobalNews.png", "tvg-name": "寰宇新闻", "name": "寰宇新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/asiatravel.png", "tvg-name": "亚洲旅游台", "name": "亚洲旅游台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/medici-arts.png", "tvg-name": "梅迪奇艺术", "name": "梅迪奇艺术"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sports_net_2.png", "tvg-name": "博斯运动二台",
     "name": "博斯运动二台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport_tennis.png", "tvg-name": "博斯网球台", "name": "博斯网球台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport_unlimited.png", "tvg-name": "博斯无限台",
     "name": "博斯无限台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sports-golfch.png", "tvg-name": "博斯高球1台",
     "name": "博斯高球1台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport-golfplus.png", "tvg-name": "博斯高球2台",
     "name": "博斯高球2台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport-trendsport.png", "tvg-name": "博斯魅力网",
     "name": "博斯魅力网"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport-sports_net.png", "tvg-name": "博斯运动一台",
     "name": "博斯运动一台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/sport_unlimited2.png", "tvg-name": "博斯无限二台",
     "name": "博斯无限二台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BLUEAntExtreme.png", "tvg-name": "BlueAntExtreme",
     "name": "BlueAnt超极娱乐"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/euronews.png", "tvg-name": "Euronews", "name": "欧洲新闻"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Nickelodeon.png", "tvg-name": "Nickelodeon",
     "name": "尼克儿童频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/NickJr.png", "tvg-name": "NickJr.", "name": "小尼克频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/davinci.png", "tvg-name": "达文西频道", "name": "达文西频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CBeebies.png", "tvg-name": "CBeebies", "name": "CBeebies"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BOOMERANG.png", "tvg-name": "Boomerang", "name": "Boomerang"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/BBCEarth.png", "tvg-name": "BBCEarth", "name": "BBC,Earth"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖洋卡通.png", "tvg-name": "靖洋卡通台", "name": "靖洋卡通台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天卡通.png", "tvg-name": "靖天卡通台", "name": "靖天卡通台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/SETZonghe.png", "tvg-name": "三立综合台", "name": "三立综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/QSKX.png", "tvg-name": "求索科学", "name": "华数求索科学"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CHC3.jpg", "tvg-name": "CHC高清电影", "name": "CHC高清电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/QSDW.png", "tvg-name": "求索动物", "name": "华数求索动物"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/QSJL.png", "tvg-name": "求索记录", "name": "华数求索记录"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CHC1.jpg", "tvg-name": "CHC动作电影", "name": "CHC动作电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CHC2.jpg", "tvg-name": "CHC家庭电影", "name": "CHC家庭电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE20.jpg", "tvg-name": "梨园", "name": "中数梨园"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVfengyunyinyue.png", "tvg-name": "风云音乐",
     "name": "中数风云音乐"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVdiyijuchang.png", "tvg-name": "第一剧场",
     "name": "中数第一剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTBfengyun.png", "tvg-name": "风云剧场", "name": "中数风云剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVshijiedili.png", "tvg-name": "世界地理",
     "name": "中数世界地理"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE7.jpg", "tvg-name": "怀旧剧场", "name": "中数怀旧剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE8.jpg", "tvg-name": "兵器科技", "name": "中数兵器科技"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVnvxing.png", "tvg-name": "女性时尚", "name": "中数女性时尚"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVyule.png", "tvg-name": "CCTV-娱乐", "name": "中数CCTV-娱乐"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVxiqu.png", "tvg-name": "CCTV-戏曲", "name": "中数CCTV-戏曲"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE13.jpg", "tvg-name": "高尔夫网球",
     "name": "中数高尔夫网球"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVwenhuajingpin.png", "tvg-name": "央视精品",
     "name": "中数央视精品"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/caiminzaixian.png", "tvg-name": "彩民在线", "name": "中数彩民在线"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE22.jpg", "tvg-name": "汽摩", "name": "中数汽摩"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE24.jpg", "tvg-name": "留学世界", "name": "中数留学世界"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE25.jpg", "tvg-name": "青年学苑", "name": "中数青年学苑"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/PHOTOGRAPHY-CHANNEL.jpg", "tvg-name": "摄影频道",
     "name": "中数摄影频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/TIANYUANWEIQI.jpg", "tvg-name": "天元围棋", "name": "中数天元围棋"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE29.png", "tvg-name": "现代女性", "name": "中数现代女性"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE33.jpg", "tvg-name": "早期教育", "name": "中数早期教育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVzhengquan.png", "tvg-name": "证券资讯",
     "name": "中数CCTV证券资讯"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVtaiqiu.png", "tvg-name": "央视台球",
     "name": "中数CCTV央视台球"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/DOCUMENTARY-CHANNEL.jpg", "tvg-name": "茶频道",
     "name": "中数茶频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WUSHUSHIJIE.jpg", "tvg-name": "武术世界", "name": "中数武术世界"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVfaxianzhilv.png", "tvg-name": "发现之旅",
     "name": "中数发现之旅"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HUANQIUQIGUAN.jpg", "tvg-name": "环球奇观", "name": "中数环球奇观"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/SHUOWENJIEZI.jpg", "tvg-name": "国学", "name": "中数国学"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/WENWUBAOKU.jpg", "tvg-name": "文物宝库", "name": "中数文物宝库"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVxinke.png", "tvg-name": "新科动漫", "name": "中数新科动漫"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/YOUERJIAOYU.jpg", "tvg-name": "幼儿教育", "name": "中数幼儿教育"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVlaogushi.png", "tvg-name": "老故事",
     "name": "中数CCTV老故事"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/KUAILECHUIDIAO.jpg", "tvg-name": "快乐垂钓",
     "name": "中数快乐垂钓"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE37.jpg", "tvg-name": "书画频道", "name": "中数书画频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/XFBY.png", "tvg-name": "先锋乒羽", "name": "华诚先锋乒羽"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC1.jpg", "tvg-name": "车迷频道", "name": "北广车迷频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC4.jpg", "tvg-name": "四海钓鱼", "name": "北广四海钓鱼"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC6.jpg", "tvg-name": "环球旅游", "name": "北广环球旅游"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC8.jpg", "tvg-name": "京视剧场", "name": "北广京视剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC10.jpg", "tvg-name": "弈坛春秋", "name": "北广弈坛春秋"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC14.jpg", "tvg-name": "央广健康", "name": "北广央广健康"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC17.jpg", "tvg-name": "时代家居", "name": "北广时代家居"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC18.jpg", "tvg-name": "时代出行", "name": "北广时代出行"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/BAMC19.jpg", "tvg-name": "时代风尚", "name": "北广时代风尚"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/财富天下.png", "tvg-name": "财富天下", "name": "北广财富天下"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/CHTV.jpg", "tvg-name": "百姓健康", "name": "北广百姓健康"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HSJPJC.jpg", "tvg-name": "精品剧场", "name": "华数精品剧场"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/HSSEDM.jpg", "tvg-name": "少儿动漫", "name": "华数少儿动漫"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/OMYY.jpg", "tvg-name": "欧美影院", "name": "华数欧美影院"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/abcaus.png", "tvg-name": "ABCAustralia", "name": "ABCAustralia"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/nhkworldp.png", "tvg-name": "NHKWorldPremium",
     "name": "NHKWorldPremium"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/hkguojicaijing.png", "tvg-name": "香港国际财经台",
     "name": "香港国际财经台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/hongkongkai.png", "tvg-name": "香港开电视", "name": "香港开电视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/youxiancaijingzixun.png", "tvg-name": "有线财经资讯台",
     "name": "有线财经资讯台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/zhujiang.png", "tvg-name": "珠江频道", "name": "珠江频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华偶像.png", "tvg-name": "龙华偶像", "name": "龙华偶像"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华戏剧.png", "tvg-name": "龙华戏剧", "name": "龙华戏剧"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华电影.png", "tvg-name": "龙华电影", "name": "龙华电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华经典.png", "tvg-name": "龙华经典", "name": "龙华经典"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华影剧.png", "tvg-name": "龙华影剧", "name": "龙华影剧"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华洋片.png", "tvg-name": "龙华洋片", "name": "龙华洋片"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ftv-1.png", "tvg-name": "民视第一台", "name": "民视第一台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ftv-taiwan.png", "tvg-name": "民视台湾台", "name": "民视台湾台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/民视.png", "tvg-name": "民视", "name": "民视"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/中视菁采.png", "tvg-name": "中视菁采台", "name": "中视菁采台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/TVBS精采.png", "tvg-name": "TVBS精采台", "name": "TVBS精采台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ELTA_Ent.png", "tvg-name": "爱尔达娱乐台", "name": "爱尔达娱乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ftv-zongyi.png", "tvg-name": "民视综艺台", "name": "民视综艺台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/huayimbc.png", "tvg-name": "华艺MBC", "name": "华艺MBC综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/traceurban.png", "tvg-name": "TRACEUrban", "name": "TRACE,Urban"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/elevensports2.png", "tvg-name": "ELEVEN体育二台",
     "name": "ELEVEN体育二台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/fashionone.png", "tvg-name": "FashionOne", "name": "Fashion,One"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/HistoryChannel.png", "tvg-name": "History",
     "name": "History,历史频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/Smart知识台.png", "tvg-name": "SMART知识频道",
     "name": "SMART,知识频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/龙华日韩.png", "tvg-name": "龙华日韩台", "name": "龙华日韩台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天戏剧.png", "tvg-name": "靖天戏剧台", "name": "靖天戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天电影.png", "tvg-name": "靖天电影台", "name": "靖天电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/AMC.png", "tvg-name": "AMC", "name": "AMC"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/中视经典.png", "tvg-name": "中视经典", "name": "中视经典台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ifun1.png", "tvg-name": "iFun1", "name": "i-Fun动漫台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ifun3.png", "tvg-name": "iFun3", "name": "i-Fun动漫2台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/中视新闻.png", "tvg-name": "中视新闻", "name": "中视新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/CrimeInvestigation.png", "tvg-name": "CI",
     "name": "CI,罪案侦查频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/cnex.png", "tvg-name": "cnex", "name": "视纳华仁纪实频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/采昌影剧.png", "tvg-name": "采昌影剧", "name": "采昌影剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/智林体育台.png", "tvg-name": "智林体育", "name": "智林体育台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/aljazeera.png", "tvg-name": "aljazeera", "name": "半岛国际新闻台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/影迷纪实.png", "tvg-name": "影迷数位纪实",
     "name": "影迷数位纪实台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/影迷电影.png", "tvg-name": "影迷数位电影",
     "name": "影迷数位电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eltv.png", "tvg-name": "ELTV", "name": "ELTV生活英语台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/靖天国际.png", "tvg-name": "靖天国际", "name": "KLT靖天国际"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/longhuadonghua.png", "tvg-name": "龙华动画", "name": "龙华动画"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/MTV.png", "tvg-name": "MTV综合", "name": "MTV综合电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/elta_sports2.png", "tvg-name": "爱尔达体育2",
     "name": "爱尔达体育2台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/luxetv.png", "tvg-name": "LUXETV", "name": "LUXE,TV,Channel"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/roller.png", "tvg-name": "rollor", "name": "滚动力,rollor"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/asiazonghe.png", "tvg-name": "亚洲综合", "name": "亚洲综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/huanyuzonghe.png", "tvg-name": "寰宇HD综合",
     "name": "寰宇HD综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/weilaojingcai.png", "tvg-name": "纬来精采", "name": "纬来精采台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/etoday.png", "tvg-name": "Ettoday", "name": "ETtoday综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/badayou.png", "tvg-name": "八大优", "name": "八大优频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/taiwanxiju.png", "tvg-name": "台湾戏剧", "name": "台湾戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/elta_yingju.png", "tvg-name": "爱尔达影剧", "name": "爱尔达影剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/my101.png", "tvg-name": "MY101综合", "name": "MY101综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/starmovieyule.png", "tvg-name": "星卫娱乐", "name": "星卫娱乐台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/huanyucaijing.png", "tvg-name": "寰宇财经", "name": "寰宇财经台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/catchplay.png", "tvg-name": "CatchPlay电影",
     "name": "CatchPlay电影台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/MyCinemaEurope.png", "tvg-name": "MyCinemaEurope",
     "name": "我的欧洲电影"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tfc.png", "tvg-name": "TFC", "name": "TFC(ABS-CBN)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/mykids.png", "tvg-name": "MY-KIDS", "name": "MY-KIDS,TV"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eata_sports1.png", "tvg-name": "爱尔达体育1",
     "name": "爱尔达体育1台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eata_sports3.png", "tvg-name": "爱尔达体育3",
     "name": "爱尔达体育3台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eurosport.png", "tvg-name": "EUROSPORT", "name": "EUROSPORT"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/fooldplanet.png", "tvg-name": "美食星球", "name": "美食星球频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eyelvyou.png", "tvg-name": "EYE旅游", "name": "EYE,TV旅游台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/elta_zonghehd.png", "tvg-name": "爱尔达综合",
     "name": "爱尔达综合台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/tiantian.png", "tvg-name": "天天电视", "name": "天天电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/setxiju.png", "tvg-name": "三立戏剧", "name": "三立戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/eyexiju.png", "tvg-name": "EYE戏剧", "name": "EYE,TV戏剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/mandi_japan.png", "tvg-name": "曼迪日本", "name": "曼迪日本台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/StarMoviesHD.png", "tvg-name": "StarMoviesHD",
     "name": "Star,Movies,HD(MOD)"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/huayi_yingju.png", "tvg-name": "华艺影剧", "name": "华艺影剧台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/weixin.png", "tvg-name": "唯心电视", "name": "唯心电视台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/ANIMAX.png", "tvg-name": "Animax", "name": "Animax"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/gt/hongkong603.png", "tvg-name": "香港603", "name": "香港有线603"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/qt/中国教育4台.png", "tvg-name": "中国教育4台", "name": "中国教育4台"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/CCTV/CCTV16.png", "tvg-name": "CCTV16", "name": "CCTV奥林匹克频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTVMOV.png", "tvg-name": "广东影视", "name": "广东影视频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTVENT.png", "tvg-name": "广东综艺", "name": "广东综艺频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTVECO.png", "tvg-name": "广东经济",
     "name": "广东经济科教频道"},
    {"tvg-logo": "http://epg.51zmt.top:8000/tb1/sheng/GDTVSHAO.png", "tvg-name": "广东少儿", "name": "广东少儿频道"}
]


def get_channel_by_tvg_name(tvg_name):
    channel = [channel for channel in channel_list if channel['tvg-name'] == tvg_name]
    return channel[0] if len(channel) > 0 else None


def get_channel_by_name(name):
    channel = [channel for channel in channel_list if channel['name'] == name]
    return channel[0] if len(channel) > 0 else None


if __name__ == '__main__':
    r = get_channel_by_name("CCTV-2财经")
    print(r)